// PRODUCT Actions
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

// FILTER Actions
export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER';