// PRODUCT Actions
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';

// FILTER Actions
export const SET_PRODUCT_FILTER = 'SET_PRODUCT_FILTER';

// CART Actions
export const START_CART_OPERATION = 'START_CART_OPEARTION';

export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const CLEAR_CART_SUCCESS = 'CLEAR_CART_SUCCESS';

export const CART_OPERATION_FAIL = 'CART_OPERATION_FAIL';